DROP TABLE `accounts_payable`;--> statement-breakpoint
DROP TABLE `accounts_receivable`;--> statement-breakpoint
DROP TABLE `action_tracker`;--> statement-breakpoint
DROP TABLE `ai_reminders`;--> statement-breakpoint
DROP TABLE `archived_items`;--> statement-breakpoint
DROP TABLE `attachments`;--> statement-breakpoint
DROP TABLE `attendance`;--> statement-breakpoint
DROP TABLE `attendance_records`;--> statement-breakpoint
DROP TABLE `budgets`;--> statement-breakpoint
DROP TABLE `currency_rates`;--> statement-breakpoint
DROP TABLE `customer_interactions`;--> statement-breakpoint
DROP TABLE `customers`;--> statement-breakpoint
DROP TABLE `daily_sales`;--> statement-breakpoint
DROP TABLE `dashboard_insights`;--> statement-breakpoint
DROP TABLE `departments`;--> statement-breakpoint
DROP TABLE `employee_confidential`;--> statement-breakpoint
DROP TABLE `employee_kpis`;--> statement-breakpoint
DROP TABLE `employee_roles`;--> statement-breakpoint
DROP TABLE `employees`;--> statement-breakpoint
DROP TABLE `idea_notes`;--> statement-breakpoint
DROP TABLE `income_expenditure`;--> statement-breakpoint
DROP TABLE `job_descriptions`;--> statement-breakpoint
DROP TABLE `leave_applications`;--> statement-breakpoint
DROP TABLE `leave_balances`;--> statement-breakpoint
DROP TABLE `leave_requests`;--> statement-breakpoint
DROP TABLE `marketing_campaigns`;--> statement-breakpoint
DROP TABLE `marketing_content`;--> statement-breakpoint
DROP TABLE `module_permissions`;--> statement-breakpoint
DROP TABLE `monthly_sales_targets`;--> statement-breakpoint
DROP TABLE `notification_log`;--> statement-breakpoint
DROP TABLE `payroll_records`;--> statement-breakpoint
DROP TABLE `performance_reviews`;--> statement-breakpoint
DROP TABLE `positions`;--> statement-breakpoint
DROP TABLE `project_transactions`;--> statement-breakpoint
DROP TABLE `projects`;--> statement-breakpoint
DROP TABLE `quotation_items`;--> statement-breakpoint
DROP TABLE `sales`;--> statement-breakpoint
DROP TABLE `sales_products`;--> statement-breakpoint
DROP TABLE `sales_tracking`;--> statement-breakpoint
DROP TABLE `system_settings`;--> statement-breakpoint
DROP TABLE `team_members`;--> statement-breakpoint
DROP TABLE `tender_quotation`;--> statement-breakpoint
DROP TABLE `transaction_types`;--> statement-breakpoint
DROP TABLE `weekly_sales_targets`;--> statement-breakpoint
ALTER TABLE `users` MODIFY COLUMN `role` enum('user','admin') NOT NULL DEFAULT 'user';